### ISSUE TITLE
VDR shows the channelinfo from Kodi (VNSI) and not its own

### ISSUE THREAD

**Issue by motorsense** [FernetMenta/vdr-plugin-vnsiserver#90] opened 2017-04-11 16:44 UTC
Hello,
I watch TV on my VDR and if a Kodi client connect via VNSI the channelinfo (from the channel there is watched with Kodi) pop up on VDR. If i now press the button for Channelinfo on VDR, they also show the channelinfo of the Kodi client. In addition if I change the Channel on VDR it does not go to the next channel according to VDR but according to Kodi client.

See http://www.vdr-portal.de/board16-video-disk-recorder/board99-distributionen/board96-yavdr/130538-umschalten-vnsi-client/?s=c570a380397b40d191fbd7810b823d11ece8c990

**Comment by FernetMenta** [comment] 2017-04-13 05:53
The problem was that VDR has treated "live view", that is the mode vdr thinks it plays the channel on the server, differently to non-live. Channls that require a CAM did not start properly. Maybe this improved with VDR 2.3.3 and can be changed now.

**Comment by 3PO** [comment] 2018-01-29 16:52
This problem still exists in vdr-2.3.8.

The behavior comes if someone (-> in this case vnsiserver) changes the "CurrentChannel" of the VDR.

I'm not sure, but i think this happens in "videoinput.c".

    ...
        if (m_Device->SwitchChannel(m_Channel, false))
        {
    
          m_Device->SetCurrentChannel(m_Channel);
    ...

Is it really necessary that vnsi do this?

**Comment by FernetMenta** [comment] 2018-02-07 15:48
I dropped this line:
https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/31c8f71538ddb9aeff23578e7464328576ef3a2b

**Comment by 3PO** [comment] 2018-02-07 18:48
After a short test it seems the issue is solved, so you can close this. 

Thanks!

**Closed** 2018-02-07 19:18 UTC
