### ISSUE TITLE
How to get back "VDR grouping" in the recording list?

### ISSUE THREAD

**Issue by M-Reimer** [FernetMenta/vdr-plugin-vnsiserver#85] opened 2017-01-29 10:35 UTC
Hello,
I'm no longer able to get my recording list to exact the same grouping as on the VDR side.
Maybe this has something to do with this commit? 
https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/44829e9d48b27e2437963523a6cd371b023b6d73
Is there any way to get back the old behaviour? I have some auto-timers which sort recordings to specific directories. I would like to have exactly this grouping in Kodi.
Thanks in advance.

**Comment by FernetMenta** [comment] 2017-01-29 10:53
can you give an example how this looks like and what you expect it to be?

**Comment by M-Reimer** [comment] 2017-01-29 10:55
I just want the *exactly same* recording structure from VDR in Kodi.
Means: If I have subdirectories on VDR side, I want the same subdirectories on Kodi, too.
This worked so far, but I have updated the VDR plugin, so I guess this may be the reason that Kodi now has its own recording structure.

**Comment by FernetMenta** [comment] 2017-01-29 11:07
The only thing that changed is that recordings can now be grouped by kodi. Prior to this change series recordings were displayed flat although they were grouped by vdr. vdr has it like this:

"name of series" as folder
- episode x.rec
- episode y.rec

Now Kodi can group those episodes under the series name. That's all that changed. I am not aware of any issues. That's why I asked for a detailed description.

**Comment by M-Reimer** [comment] 2017-01-29 11:41
VDR has completely free grouping. It's my choice where I place subdirectories. It's even possible to have multiple levels of subdirectories. This is even possible via the VDR OSD, but not that simple. It's much easier to just do it on the file system (create the wanted directory structure).
So far I had the directories, I'm used to, on the top of the list in Kodi and the "ungrouped" recordings after that. Now my self-defined groups are gone and everything is "auto-grouped".
Difficult to describe, so I'll provide two screenshots:
![kodi-recordings](https://cloud.githubusercontent.com/assets/3519517/22403716/26770816-e620-11e6-96c6-5c86f2d48187.png)
![vdr-recordings](https://cloud.githubusercontent.com/assets/3519517/22403715/26750246-e620-11e6-8c3e-e1f1d5e27e1c.png)
I have free options on how I want to group my recordings on "VDR-side" if not via OSD, then I may do it directly on the file system. It would be nice if this completely free custom grouping could (at least optionally) be reflected to the Kodi OSD.

**Comment by FernetMenta** [comment] 2017-01-29 12:27
I created this structure on my VDR system. House-Top is a folder I manually created:
![image](https://cloud.githubusercontent.com/assets/576009/22403927/f34fc116-e625-11e6-8933-db57215f8474.png)

Kodi I have the same:
![image](https://cloud.githubusercontent.com/assets/576009/22403937/2e370262-e626-11e6-9997-f6cc1b7453ae.png)

Kodi does exactly show the filesystem structure of the VideoDir of VDR.

Isn't this what you want it to be?

**Comment by M-Reimer** [comment] 2017-01-29 12:37
Then maybe there is a problem with my settings.
I don't get *exactly* the same grouping to Kodi as I have in VDR.
For example, if I for whatever reason decide to have some recordings in a directory just called "A" and some in one called "B", then I want *exactly this* in Kodi and no Auto-Grouping based on some meta data.
How can I get this back?

**Comment by M-Reimer** [comment] 2017-01-29 12:42
Screenshot of my recording menu sort/group settings:
![vdr-recordings-settings](https://cloud.githubusercontent.com/assets/3519517/22404052/bcee0b52-e628-11e6-81a7-73eb10b76886.png)

**Comment by FernetMenta** [comment] 2017-01-29 12:45
There is no auto-grouping based on metadata. It has ever been the folder structure of VDR. Please elaborate on what you call "auto-grouping". How does such a grouping show?

**Comment by M-Reimer** [comment] 2017-01-29 12:47
My directory structure ist just "gone". Seems like new directories are auto-generated based on the recording title. If I just uncheck "Group Items", then *all* directories are gone. Even the auto-generated ones. I have this problem on two Kodi systems and I don't know how to get back to the old behaviour...
May it be some incompatibility between latest changes and Kodi 16?

**Comment by FernetMenta** [comment] 2017-01-29 12:59
> May it be some incompatibility between latest changes and Kodi 16?

that could be the case. could you try v17?

**Comment by M-Reimer** [comment] 2017-01-29 13:06
No. Too much trouble as my distributor doesn't ship it and no time at all to compile everything involved in a test... :(

**Comment by M-Reimer** [comment] 2017-01-29 13:20
Downgraded to VDR plugin version 1.5.0 and I have my old grouping back...

**Comment by FernetMenta** [comment] 2017-01-29 13:26
v17 will be released in a couple of days. then you distro should ship it.

**Comment by M-Reimer** [comment] 2017-01-29 13:29
Maybe, but even after that there will be many V16 installations out there.
For future stable versions: Could you perhaps also split the VDR plugin tree to two branches. One you keep updated to work with the stable version and one which is meant to be used with the current development version?

**Comment by M-Reimer** [comment] 2017-01-29 13:30
But after thinking about it... Especially if there are many clients in one setup and they run with different distributions on different platforms, it would be better to have a "version neutral" protocol on VDR side...

**Comment by FernetMenta** [comment] 2017-01-29 13:41
I would rather fix the root cause and as a first step I need to if the issue is somehow related to your installation or incompatibility to v16. The latter is just an assumption and not proven.

**Comment by M-Reimer** [comment] 2017-01-29 13:48
I'm currently flashing LibreElec Beta to my Raspberry SD card. Should be able to do a short Kodi 17 test with that.

**Comment by M-Reimer** [comment] 2017-01-29 14:07
Tried it. Have the same problem with V17...
Settings:
"Sort by" --> "Date"
"Order" --> "Descending"
"Group Items" --> "Yes"

Still have "pseudo-folders" based on the recording title and not the folders which are delivered by VDR...
I'm running VDR 2.2.0 (stable) if this matters.

**Comment by M-Reimer** [comment] 2017-01-29 14:10
Downgraded to Version 1.5.1 and now I have the expected grouping in both, Kodi 16 and Kodi 17.
So:
First bad version: 1.5.2
Last good version: 1.5.1

**Comment by M-Reimer** [comment] 2017-01-29 14:14
It may also be possible that what I see is a mix of my custom created directories and more of them "virtually created but non-existent". For example recordings with the same title are grouped together into one folder. This is the behaviour I want to get rid of or would like to have configurable.

**Comment by FernetMenta** [comment] 2017-01-29 16:24
Look at my example above. Various episodes of Dr.House are located in a folder names Dr.House. The folder Dr.Hours does exist on the backend. It contains the recordings in *.rec folders. Prior to this change the folder Dr.House was not shown in Kodi.
Means that the folders you call "virtually created" are real folders.

Summary:
Kodi/vnsi displays the folders you have on disk
VDR omits the folders containing the *.rec folders

Can you confirm this?

**Comment by FernetMenta** [comment] 2017-01-29 17:11
If this is the case, I can make this configurable via a plugin setting.

**Comment by M-Reimer** [comment] 2017-02-05 10:01
Sorry for the late answer, but exactly this is my problem.
The "old behaviour" of your plugin was the VDR standard behaviour. VDR groups recordings, named with the same name, in one directory, but in the VDR GUI each recording is listed individually.
If you make this configurable, I would recommend to make the "old behaviour" (not displaying the folders) the new default as this is what someone, who is used to VDR and used the recording list on the VDR GUI, expects.

**Comment by FernetMenta** [comment] 2017-02-05 10:12
I don't think most kodi users with vdr backend have ever seen vdr ui. The old behaviour conflicts with kodi feature of grouping recordings. Hence the default will be current behaviour.

**Comment by M-Reimer** [comment] 2017-02-05 10:18
No problem as long as there is an option to use the "standard VDR grouping" at all.

**Comment by FernetMenta** [comment] 2017-02-25 16:43
it is configurable now: https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/aef3380bad579f5ec3bf72f2925572c58f5a2007

**Closed by FernetMenta** 2017-02-25 16:43 UTC
